### ISSUE TITLE
About th02~05 Music Room

### ISSUE THREAD

**Issue by ROCO-freedom** [nmlgc/ReC98#5]
I recently did a project to re-create the th2 ~ 5 music room. However, I encountered a problem, I do not know ZUN the use of the polygon background (which is the polygon inside the star image) where. So I'd like to ask you, where do you find those pictures from these data? thank you very much!

**Comment by nmlgc** [comment]
The polygons are fully created and animated in code. [I already decompiled the TH02 Music Room containing this code](https://github.com/nmlgc/ReC98/blob/master/th02/op_06.c), and that part didn't change in later games.

**Comment by ROCO-freedom** [comment]
所以，多边形里面呈现的“星空图片”，就是*.rgb文件吗？

**Comment by ROCO-freedom** [comment]
So, the polygons inside the "Star Image", is the * .rgb file?

**Comment by nmlgc** [comment]
The polygons are created and rendered by [this code](https://github.com/nmlgc/ReC98/blob/master/th02/op_06.c#L104). Since they are just regular geometric shapes, drawn in a single (transparent) color, it is very efficient to store them just in terms of their position, angle, and move/rotation speeds, and use master.lib's shape drawing functions to render them on each frame. So there are no separate files involved here, it's all code.

**Comment by ROCO-freedom** [comment]
Oh, so ZUN is by changing the code to achieve replacement pictures (th02 ~ 05 pictures are different), so I need to reconsider whether to join the polygon effect, thank you for your answer!

**Comment by nmlgc** [comment]
Just got done finalizing all Music Rooms. [This effect is now documented in more depth on the blog](https://rec98.nmlgc.net/blog/2024-02-03), as well as [in the code](https://github.com/nmlgc/ReC98/blob/master/th02/op/m_music.cpp)

**Comment by RetroCyber** [comment]
> Just got done finalizing all Music Rooms. [This effect is now documented in more depth on the blog](https://rec98.nmlgc.net/blog/2024-02-03), as well as [in the code](https://github.com/nmlgc/ReC98/blob/master/th02/op/m_music.cpp).

Glad to know about this, thx for ur hard work!☺️
